algoritmo "semnome"
// Função :
// Autor :
// Data : 29/04/2022
// Seção de Declarações 
var
nomedoaluno:caracter
nota1,nota2,nota3:real
media:real
inicio
// Seção de Comandos 
escreval("digite o nome do aluno")
leia(nomedoaluno)
escreval("digite a nota 1")
leia(nota1)
escreval("digite a nota2")
leia(nota2)
escreval("digite a nota3")
leia(nota3)
media<-(nota1+nota2+nota3)/3
escreval("o aluno:"+nomedoaluno)
escreva("obteve a media:")
escreval(media)
fimalgoritmo
