Algoritmo "semnome"

Var
distancia:inteiro
media:real
gasolina:inteiro
Inicio
escreval("--------------------------------------")
escreval("digite a distancia(km)")
leia(distancia)
escreval("digite a quantidade de gasolina")
leia(gasolina)
media<-gasolina/distancia
escreval("--------------------------------------")
escreval("o consumo medio de gasolina por km é")
escreva(media)
escreva(" ")
escreval("litros")
Fimalgoritmo