Algoritmo "semnome"

Var
nome:caracter
nota1,nota2,nota3:inteiro
media:real
i:inteiro
Inicio
escreval("------------------------------------------")
escreval("digite o nome do aluno")
leia(nome)
escreval("------------------------------------------")
escreval("digite a nota 1")
leia(nota1)
escreval("------------------------------------------")
escreval("digite a nota 2")
leia(nota2)
escreval("------------------------------------------")
escreval("digite a nota 3")
leia(nota3)
media<-(nota1+nota2+nota3)/3
escreval("------------------------------------------")
escreva("o aluno:")
escreval(nome)
escreva("obteve a media:")
escreval(media)
Fimalgoritmo