Algoritmo "semnome"

Var
reais:inteiro
cotacao:inteiro
dolar:real
Inicio
escreval("--------------------------------")
escreval("digite o valor em reais")
leia(reais)
escreval("digite a cotacao")
leia(cotacao)
dolar<-reais/cotacao
escreval("--------------------------------")
escreva("o valor:")
escreva(reais)
escreval(" reais")
escreval("vale em dolar:")
escreval(dolar)
Fimalgoritmo